---
title: "tumor_vs_normal_cleanup_desription"
author: "Felipe Stünkel"
date: "21 5 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#1 reorganize
```{r install all packages}
#install.packages("gridExtra")
#install.packages("gtools")
library(ggplot2)
library(scales)
library("gridExtra")
library(gtools)
library(biomaRt)
library(parallel)
library(grid)
```
```{r loading data & extraction}
#load data
tumor_vs_norm <- readRDS("./data/tcga_tumor_normal_datascience_proj_2022.RDS")

#extract info from list
luad = tumor_vs_norm[["LUAD"]]
luad.tumor = luad[["tumor"]]
luad.normal = luad[["normal"]]
luad.anno = luad[["clinical"]]
luad.tumor = as.data.frame(t(luad.tumor)) # transponieren der dataframe, sodass (cols = Gene) und (rows = Patienten)
luad.normal = as.data.frame(t(luad.normal)) # ...PCA erkennt cols als variablen und rows als samples

rm(tumor_vs_norm)
```
```{r NA check}
#checking NA´s
sum(is.na(luad.normal)) # 0 NA´s
sum(is.na(luad.tumor)) # "-"
sum(is.na(luad.anno)) # 148 NA´s
NA_sources <- apply(luad.anno, 2, function(x){sum(is.na(x))})
NA_sources = NA_sources[which(NA_sources > 0)]
NA_sources # NA sources not sign.


rm(luad, NA_sources)
```


#2 cleanup & descriptive
##2.1 cleanup
```{r df: mean, mediean, var. (...)}
#1. create new data frame with mean, median and variance information of each gen
mmv_df = data.frame(med.normal = apply(luad.normal, 2, median),
                    med.tumor = apply(luad.tumor, 2, median),
                    mean.normal = colMeans(luad.normal),
                    mean.tumor = colMeans(luad.tumor),
                    var.normal = apply(luad.normal, 2, var),
                    var.tumor = apply(luad.tumor, 2, var)
                    )
mmv_df$diff.med = c(mmv_df$med.tumor-mmv_df$med.normal)
mmv_df$diff.mean = c(mmv_df$mean.tumor-mmv_df$mean.normal)

View(head(mmv_df))# rows = gen ID´s, cols =conditions

```
```{r remove 0 var. genes}

# 1: removing all low variance genes, below p% quantile from mmv_df_new
p = c(.5, .9)
x = quantile(mmv_df$var.normal, probs = p[1], names = F)
mmv_df_new = mmv_df[mmv_df$var.normal > x,]

#2: removing all the gens under 50% quantile from luad.normal and luad.tumor:
genenames = rownames(mmv_df_new)
luad.normal.new = luad.normal[,genenames]# new df with removed 50% quantile values
dim(luad.normal.new)#  58 9812
# 1: removing all low varriance gens, below p% quantile from mmv_df_new
#p = c(.5, .9)
#x = quantile(mmv_df$var.normal, probs = p[1], names = F)
#mmv_df_new = mmv_df[mmv_df$var.normal > x,]

#2: removing all the gens under 50% quantile from luad.normal and luad . tumor:
#genenames = rownames(mmv_df_new)
#luad.normal.new = luad.normal[,genenames]# new df with removed 50% quantile values
#dim(luad.normal.new)#  58 9812

#luad.tumor.new = luad.tumor[,genenames]

#3: removing all genes with var = 0 (otherwise shapiro test won´t work)
zero.var = rownames(mmv_df_new[which(mmv_df_new$var.tumor != 0),])

luad.normal.cut = luad.normal.new[,zero.var]# luad.normal without the var =0 gens from tumor
luad.tumor.cut = luad.tumor.new[,zero.var]# luad.tumor without the var = 0 gens
mmv_df_cut = mmv_df_new[zero.var,]# mmv_df without the var = 0 gens

#checking for remaining 0 var.genes
paste("there are", sum(which(mmv_df_cut$var.normal == 0)), "zero var.genes remaining")
paste("there are", sum(which(mmv_df_cut$var.tumor == 0)), "zero var.genes remaining")

rm(mmv_df, luad.normal, luad.tumor, genenames, p, x, zero.var, luad.normal.new, luad.tumor.new, mmv_df_new)
#3: removing all gens with varr = 0 (otherwise shapiro test won´t work)
#3.1: tumor
rows = c(which(mmv_df$var.tumor != 0))
zero.var = rownames(mmv_df[rows,])
length(zero.var)

luad.normal.cut = luad.normal[,zero.var]# luad. normal without the varr =0 gens from tumor
luad.tumor.cut = luad.tumor[,zero.var]# luad. tumor without the varr = 0 gens
mmv_df_cut = mmv_df[zero.var,]# mmv_df without the varr = 0 gens

#3.2: normal
rows = c(which(mmv_df_cut$var.normal != 0))
zero.var = rownames(mmv_df_cut[rows,])
length(zero.var)

luad.normal.cut = luad.normal.cut[,zero.var]# luad. normal without the varr =0 gens from tumor
luad.tumor.cut = luad.tumor.cut[,zero.var]# luad. tumor without the varr = 0 gens
mmv_df_cut = mmv_df_cut[zero.var,]# mmv_df without the varr = 0 gens





#checking for remaining 0 var. genes
paste("there are", length(which(mmv_df_cut$var.normal == 0)), "zero var. genes remaining")
paste("there are", length(which(mmv_df_cut$var.tumor == 0)), "zero var. genes remaining")

rm(mmv_df, luad.normal, luad.tumor, zero.var, rows)
```
```{r remove biotypes}
#---------------------------------------------#
# please save: saveRDS(metabolism_list_gs, "./data/metabolism_list_gs.RDS")
#taken from metabolic.pathways.Rmd
#---------------------------------------------#
metabolism_list_gs = readRDS("./data/metabolism_list_gs.RDS") 




IDs.cut = c()
for(i in colnames(luad.tumor.cut)){
  IDs.cut = c(IDs.cut, strsplit(i, "|", fixed = T)[[1]][2])
}
colnames(luad.tumor.cut) = make.names(IDs.cut, unique = T)
colnames(luad.normal.cut) = make.names(IDs.cut, unique = T)
rownames(mmv_df_cut) = make.names(IDs.cut, unique = T)

ensembl <- useEnsembl(biomart = "ensembl", dataset = "hsapiens_gene_ensembl")
biotypes <- getBM(mart = ensembl, values = IDs.cut, filters = "external_gene_name", attributes = c("gene_biotype", "external_gene_name"))
head(biotypes)
# shows all biotypes in our data!!!!!!!!!!!!!!!!!!!
unique(biotypes$gene_biotype)


#which biotypes in our gensets?
genesets <- readRDS("./data/hallmarks_genesets.rds")
biotypes_hallmarks <- getBM(mart = ensembl, values = unique(unlist(genesets$genesets, use.names = FALSE)), filters = "hgnc_symbol", attributes = c("gene_biotype", "ensembl_gene_id", "hgnc_symbol"))
relevant_biotypes <- levels(as.factor(biotypes_hallmarks$gene_biotype))

biotypes_metabol <- getBM(mart = ensembl, values = unique(unlist(metabolism_list_gs, use.names = FALSE)), filters = "hgnc_symbol", attributes = c("gene_biotype", "ensembl_gene_id", "hgnc_symbol"))
relevant_biotypes <- unique(append(relevant_biotypes, levels(as.factor(biotypes_metabol$gene_biotype))))

#lets get the biotypes that are relevant for us
biotypes.cut = biotypes[which(biotypes$gene_biotype %in% relevant_biotypes),]

head(biotypes.cut)
left.genes = biotypes.cut$external_gene_name
head(left.genes)#these are the gens we want 

#get them out of luad.normal & luad.tumor
colnames = colnames(luad.normal.cut)[which(colnames(luad.normal.cut) %in% left.genes)]
luad.normal.clean = luad.normal.cut[,colnames]
luad.tumor.clean = luad.tumor.cut[,colnames]
mmv_df_clean = mmv_df_cut[colnames,]

dim(mmv_df_clean)
View(head(mmv_df_clean))

#view biotypes
biotype.freq = as.data.frame(sort(table(biotypes.cut$gene_biotype)))

ggplot(biotype.freq, aes(x=Var1, y = Freq))+
  geom_col()+
  coord_flip()+
  xlab("biotypes")+
  ylab("Frequency") +
  scale_y_continuous(trans = 'log10')+
  annotation_logticks(sides="b") # logticks on the b_ottom


rm(biotypes, biotypes_hallmarks, biotypes_metabol, biotypes.cut, genesets, luad.normal.cut, luad.tumor.cut, mmv_df_cut, colnames, i, IDs.cut, left.genes, relevant_biotypes, metabolism_list_gs, biotype.freq)
```

##2.2 descriptive
```{r mean var. plots}
g3 = ggplot(mmv_df_clean, aes(y = var.normal, x = mean.normal))+ 
  geom_point()+
  labs(title = "mean-variance plot of the normal tissue", # einfach beschriften des plots
       y = "variance", x = ("mean"))+
  geom_smooth()

g4 = ggplot(mmv_df_clean, aes(y = var.tumor, x = mean.tumor))+
  geom_point()+
  labs(title = "mean-variance plot of the tumor tissue", # einfach beschriften des plots
       y = "variance", x = ("mean"))+
  geom_smooth()

mean.varr = grid.arrange(g3, g4, nrow = 1)

rm(g3, g4, mean.varr)
```
```{r shapiro wilcon test}
# #1 test auf normalverteilung der gene: shapiro-wilcon test

#shapiro.test(luad.tumor.cut$RAB4B)$p.value # p value of one gen in tumor tissue

for (i in 1: ncol(luad.tumor.clean)){# p values for tumor tissue
 mmv_df_clean$shapiro.tumor[i] = shapiro.test(luad.tumor.clean[,i])$p.value
}
for (i in 1: ncol(luad.normal.clean)){#p values for normal tissue
  mmv_df_clean$shapiro.normal[i] = shapiro.test(luad.normal.clean[,i])$p.value
}
View(head(mmv_df_clean))

rm(i)
```
```{r view p-values of distr.}
#lets view the # normal distr. genes
p = (.5)
qt = quantile(mmv_df_clean$shapiro.tumor, probs = p, names = F)
qn = quantile(mmv_df_clean$shapiro.normal, probs = p, names = F)

a1 = ggplot(mmv_df_clean, aes(shapiro.tumor))+
  geom_density(color="darkblue", fill="lightblue")+
  labs(title = "p-value density shapiro test tumor tissue", x ="p-values", y = "density")+
  geom_vline(xintercept = 0.05, linetype="dashed")+
  geom_vline(xintercept = qt, col = "red")
  
a2 = ggplot(mmv_df_clean, aes(shapiro.normal))+
  geom_density(color="darkblue", fill="lightblue")+
  labs(title = "p-value density shapiro test normal tissue", x ="p-values", y = "density")+
  geom_vline(xintercept = 0.05, linetype="dashed")+
  geom_vline(xintercept = qn, col = "red")
normality.gens = grid.arrange(a1, a2, nrow = 1)

rm(p, qn, qt, a1, a2, normality.gens)
```
```{r wilcoxon test, }
defaultW <- getOption("warn")# don´t show warnings
options(warn = -1)




##############################################################################################
p.wilc = c(1: ncol(luad.normal.clean))
for(i in 1: ncol(luad.normal.clean)){
  p.wilc[i] = c(wilcox.test(luad.tumor.clean[,i],luad.normal.clean[,i], paired = TRUE, alternative = "two.sided" )$p.value)
  }

mmv_df_clean$p.wilc = p.wilc #-log10 tranformierte p werte, damit sie auf dem plot leichter zu sehen sind
View(head(mmv_df_clean))
##############################################################################################



options(warn = defaultW) # don´t show warnings off

rm(defaultW, i, p.wilc)
```
```{r vulcano plots}
alpha = 0.05 #punkt, ab dem die p Values signifikant werden
#alpha muss noch angepasst werden, da der test über große datenmenge durchgeführt wurde alpha.corr = alpha * 1/#gene
alpha.corr = alpha/nrow(mmv_df_clean)

for (i in 1:nrow(mmv_df_clean)){ #setting up expression
  ifelse((   (mmv_df_clean$diff.mean[i] > 0) & (-log10(mmv_df_clean$p.wilc[i]) > -log10(alpha.corr))   ), mmv_df_clean$expr[i] <- "up",
         ifelse((   (mmv_df_clean$diff.mean[i] < 0) & (-log10(mmv_df_clean$p.wilc[i]) > -log10(alpha.corr))   ),mmv_df_clean$expr[i] <- "down",
                mmv_df_clean$expr[i] <- "not sign."))
}

-log10(alpha.corr)
# plot for corrected alpha
volcano1 = ggplot(mmv_df_clean, aes(diff.mean, -log10(p.wilc), col = expr))+ #plot
  geom_point(size = .5)+
  labs(title = "volcano plot of high varicance genes -> corrected alpha", y = "-log10(p.value)", x = "log2(Foldchange)")+
  geom_hline(yintercept = -log10(alpha.corr),
             linetype = "dashed")+
  scale_color_manual(values=c("blue", "gray", "red"))

volcano1




# plot for ___NOT___ corrected alpha
for (i in 1:nrow(mmv_df_clean)){ #setting up expression
  ifelse((   (mmv_df_clean$diff.mean[i] > 0) & (-log10(mmv_df_clean$p.wilc[i]) > -log10(alpha))   ), mmv_df_clean$expr[i] <- "up",
         ifelse((   (mmv_df_clean$diff.mean[i] < 0) & (-log10(mmv_df_clean$p.wilc[i]) > -log10(alpha))   ),mmv_df_clean$expr[i] <- "down",
                mmv_df_clean$expr[i] <- "not sign."))
}

volcano2 = ggplot(mmv_df_clean, aes(diff.mean, -log10(p.wilc), col = expr))+ #plot
  geom_point(size = .5)+
  labs(title = "volcano plot of high varicance genes -> not corrected alpha ", y = "-log10(p.value)", x = "log2(Foldchange)")+
  geom_hline(yintercept = -log10(alpha),
             linetype = "dashed")+
  scale_color_manual(values=c("blue", "gray", "red"))
grid.arrange(volcano2, volcano1, nrow = 1)

rm(alpha, i, volcano1, volcano2)
```


```{r remove low diff genes and retain high diff genes}
hd = rownames(mmv_df_clean[c(mmv_df_clean$p.wilc < alpha.corr),]) # take all genes with p value < alpha.corr
length(hd)

mmv_df_end = mmv_df_clean[hd,]
luad.normal.end = luad.normal.clean[,hd]
luad.tumor.end = luad.tumor.clean[,hd]

rm(luad.normal.clean, luad.tumor.clean, hd, mmv_df_clean)

ggplot(mmv_df_end, aes(mean.normal, var.normal))+
  geom_point()# we see there are also low var genes with a significant diff in the gene expr. btw the two tissues
```
```{r volcano with remaining genes}
ggplot(mmv_df_end, aes(diff.mean, -log10(p.wilc), col = expr))+ #plot
  geom_point(size = .5)+
  labs(title = "volcano plot of high varicance genes -> corrected alpha", y = "-log10(p.value)", x = "log2(Foldchange)")+
  geom_hline(yintercept = -log10(alpha.corr),
             linetype = "dashed")+
  scale_color_manual(values=c("blue", "red"))
```

```{r saving & end & clean env.}

LUAD_tumor_vs_norm_clean = list(luad.normal.clean = luad.normal.end,
                           luad.tumor.clean = luad.tumor.end,
                           infomatrix = mmv_df_end,
                           luad.anno = luad.anno)
View(LUAD_tumor_vs_norm_clean)

saveRDS(LUAD_tumor_vs_norm_clean, "./data/LUAD_tumor_vs_norm_clean.RDS")

# now that the biotypes are removed:
paste( "There are", dim(luad.normal.end)[2], "genes left after cleaning")

rm(list=ls())
```










