---
title: "tvn gsea"
author: "Felipe St?nkel"
date: "12 7 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load all recquired packages & data}
#if you haven't yet installed fgsea package, run the following code

#if (!require("BiocManager", quietly = TRUE))
 #   install.packages("BiocManager")
#BiocManager::install("fgsea")

#to install cinaR, first run
#if (!require("BiocManager", quietly = TRUE))
    #install.packages("BiocManager")

#BiocManager::install("limma")
#if (!require("BiocManager", quietly = TRUE))
 #   install.packages("BiocManager")

#BiocManager::install("edgeR")

#install.packages("cinaR")

#to install enrichplot, first run
#if (!require("BiocManager", quietly = TRUE))
 #   install.packages("BiocManager")

#BiocManager::install("enrichplot")

#install.packages("tidyverse")

library(limma)
library(edgeR)
library(cinaR)
library(fgsea)
library(ggplot2)
library(biomaRt)
library(enrichplot)
library(tidyverse)
library(scales)
library("gridExtra")
library(gtools)
library(parallel)
library(grid)

LUAD_tumor_vs_norm_clean <- readRDS("./data/LUAD_tumor_vs_norm_clean.RDS")
luad.info = LUAD_tumor_vs_norm_clean[["infomatrix"]]
rm(LUAD_tumor_vs_norm_clean)
```

```{r sort signed pvalues which are log10 transformed}
#create a ranked gene list
ranked_gl = luad.info[rev(order(luad.info$spval)),c(14,13)]
View(head(ranked_gl))

```

```{r GSEA with splog10 (worked)}
metabolism_list_gs = readRDS("./data/metabolism_list_gs.RDS")
genesets <- readRDS("./data/hallmarks_genesets.rds")

genesets$genesets = append(genesets$genesets, metabolism_list_gs)

#stats argument (ranked p values) needs to be the right format

Values = ranked_gl$spval

names(Values) = rownames(ranked_gl)

GSEA_p = fgsea(pathways = genesets$genesets, stats = Values, scoreType = "pos")



View(GSEA_p)
(GSEA_p$padj)
#sort GSA by pvalues:

GSEA_p$rank = 1:dim(GSEA_p)[1]
ggplot(GSEA_p, aes(padj, reorder(pathway, padj)))+
  geom_point()

rm(metabolism_list_gs)
```

```{r GSEA witha all final genesets}
#all_genesets =  readRDS("C:/Users/felip/Desktop/all_final_genesets(C5).RDS")

#GSEA_p_all = fgsea(pathways = all_genesets, stats = Values, scoreType = "pos")
#for (i in 1:dim(GSEA_p_all)[1]){
 # ifelse(GSEA_p_all$pval[i] >= 0.9, GSEA_p_all$col[i] <- "not important",
  #       GSEA_p_all$col[i] <- "important")
#}


#rm(Values)

#View(GSEA_p)
#rm(ranked_gl, Values)
```

```{r}
alpha = 0.05
alpha.corr = -log10(alpha/nrow(luad.info))


z = length(genesets$genesets)
pw.v.plots = list()
pw.sv.plots = list()
pw.grad.plots = list()
name = c()
regulation = data.frame(up = c(1:z),
                        down = c(1:z),
                        not_sign = c(1:z),
                        number_of_genes = c(1:z))


for(i in 1:z){
  # select genes from one pwathway
x = i # choose pathway by position

pw = GSEA_p$pathway[x] 
pw

pw.genes = unlist(GSEA_p$leadingEdge[x], use.names = F)#genes in the pathway that are at the leading edge
genes = luad.info$name #all genes

positions = sort(match(pw.genes, genes))#compare to get positions
positions

selection = luad.info[pw.genes,] # select rows from data frame
selection$pathway = pw # make new column, called like the pw

sel = luad.info$diff.mean[positions]#select mean expr for genes in pw
mean = mean(sel)  # calculate mean expression of the pathway the genes used are the ones in the leading edge
median = median(sel)

col = c("slateblue4", "lightcoral", "slategray1", "gray84") # choosing the colours


#calculate % genes by up or down regulation
hits = paste(dim(selection)[1], "genes in", pw)
p.down = (length(which(selection$expr == "down"))/dim(selection)[1])*100
p.up = (length(which(selection$expr == "up"))/dim(selection)[1])*100

hits
percent.down = paste(round(p.down, digits = 2), "% down")
percent.up = paste(round(p.up, digits = 2), "% up")
rest = 100 - round(p.down, digits = 2) - round(p.up, digits = 2)
ns = paste(rest, "% not sign.")
vh = round(p.up/p.down, digits = 2)

#calculate for each pw the menan expression of the genes


#
##
####
##
#


###plots
#1 ) normaler v.plot
plot.v <- ggplot(luad.info, aes(y = abs(spval), diff.mean, colour = expr, label = name))+
  geom_point(size = .2)+
  labs(title = paste("volcano plot pw: ", pw), x = "fc", y = "pwilc")+
  scale_color_manual(name = "",
                     breaks = c(pw, "up", "down", "not sign."),
                     labels = c(hits, percent.up, percent.down, ns),
                     values = col )+ 
  geom_point(data = selection,
             aes(y = abs(spval), diff.mean, color = pathway), size = 2)
#2 ) singed volcano plot
plot.s = ggplot(luad.info, aes(y = spval, diff.mean, colour = expr))+
  geom_point(size = .5)+
  labs(title = paste("singed volcano plot pw: ", pw), x = "fc", y = "spval")+
  scale_color_manual(name = "",
                     breaks = c(pw, "up", "down", "not sign."),
                     labels = c(hits, percent.up, percent.down, ns),
                     values = col )+ 
  geom_point(data = selection,
             aes(y = spval, diff.mean, color = pathway), size = 2)
#3 ) gradient plot
plot.g = ggplot(luad.info, aes(spval, abs(diff.mean), colour = expr))+
  geom_point(size = .5)+
  labs(title = paste("gradient volcano plot pw: ", pw), x = "fc", y = "spval")+
  scale_color_manual(name = "",
                     breaks = c(pw, "up", "down", "not sign."),
                     labels = c(hits, percent.up, percent.down, ns),
                     values = col )+ 
  geom_point(data = selection,
             aes(spval, abs(diff.mean), color = pathway), size = 2)



###saving
pw.v.plots[[i]] <- plot.v #save the plot in the list element
pw.sv.plots[[i]] <- plot.s
pw.grad.plots[[i]] <- plot.g
message("plot saved")

regulation$up[i] = round(p.up, digits = 2)
regulation$down[i] = round(p.down, digits = 2)
regulation$not_sign[i] = rest
regulation$up_div_down[i] = vh
regulation$number_of_genes[i] = dim(selection)[1]
regulation$mean[i] = mean
regulation$median[i] = median

message("regulation filled")

name[i] <- paste(pw) #names for list elements
message("name saved")



}

#rename list elements
names(pw.v.plots) <- paste0(name)
names(pw.sv.plots) <- paste0(name)
names(pw.grad.plots) <- paste0(name)

#new list object with all plots
plots = list(pw.v.plots = pw.v.plots, 
             pw.sv.plots = pw.sv.plots,
             pw.grad.plots = pw.grad.plots,
               description = list("1" = "vcolcano plots",
                                  "2" = "signed pvals volc plots",
                                  "3" = "gradient plots"),
             regulation = regulation)
rownames(plots$regulation) <- name


View(plots$regulation)



rm( z, x, pw, pw.genes,name, genes, positions, selection, col, i, hits, p.down, p.up, percent.up,percent.down, rest, ns, pw.v.plots, pw.sv.plots, pw.grad.plots, plot.v, plot.s, plot.g, alpha, alpha.corr, mean, median, sel, vh, regulation)
```

```{r print plots information in volcano plots etc}
#grid.arrange(grobs = (plots$pw.sv.plots[1:15]))
#grid.arrange(grobs = (plots$pw.v.plots[16:30]))
#grid.arrange(grobs = (plots$pw.grad.plots[31:46]))


reg = plots$regulation

up.reg = ggplot(reg, aes(fill=up, x=up, y=rownames(reg))) +
  geom_bar(position="dodge", stat="identity")+
  scale_fill_gradient(low = "thistle1", high = "violetred4")+
  labs(title = paste("comparison of up regulated genes"), x = "up.genes/genes.in.pw", y = "pathways")+
  scale_color_manual(name = "up")+
  xlim(0,60)+
  theme(axis.text = element_text(size = 5)) 

down.reg = ggplot(reg, aes(fill=down, x=down, y=rownames(reg))) + 
  geom_bar(position="dodge", stat="identity")+
  scale_fill_gradient(low = "lightblue", high = "purple4")+
  labs(title = paste("comparison of down regulated genes"), x = "down.genes/genes.in.pw", y = "pathways")+
  scale_color_manual(name = "down")+
  xlim(0,60)+
  theme(axis.text = element_text(size = 5))

total_genes = ggplot(reg, aes(fill= number_of_genes, x = number_of_genes,
                              y=rownames(reg))) + 
  geom_bar(position="dodge", stat="identity")+
  scale_fill_gradient(low = "lightblue", high = "slategray")+
  labs(title = paste("comparison in number of genes in the leading edge"), x = "number of genes in leading edge", y = "pathways")+
  scale_color_manual(name = "count")+
  theme(axis.text = element_text(size = 5))


#log10 tf
#reg$singed_ratio = c(1:dim(reg)[1])
#for(i in 1:dim(reg)[1]){
 # ifelse(1 > reg$up_div_down[i] & reg$up_div_down[i] > 0,
  #       reg$singed_ratio[i] <- -(reg$up_div_down[i]^(-1)),
   #      reg$singed_ratio[i] <- reg$up_div_down[i]
    #     )
#  }
#reg$singed_ratio[which(reg$singed_ratio == 0)] <- -Inf

#r = c("über.expr", "unter.expr","nur.über.expr", "nur.unter.expr","gleich")# regulation info
#col = c("orange","lightblue","violetred4",  "royalblue3",  "green")

#s = ggplot(reg, aes(fill= regulation, x= singed_ratio,
  #                            y=rownames(reg)))+ 
  #scale_fill_manual(breaks = r, # regulation information
   #                   values = col)+
  #geom_bar(position="dodge", stat="identity")+
  #labs(title = paste("more up or more down reg"), x = "regution level", y = "pathways")+
  #theme(axis.text = element_text(size = 5))




for (i in 1:dim(reg)[1]){
  ifelse(reg$up_div_down[i] == 0,
         reg$up_down[i] <- "down regulated",reg$up_down[i] <- "up regulated")
}
r = c("up regulated", "down regulated")
col = c("violetred4",  "royalblue3")

s = ggplot(reg, aes(fill= up_down, x = mean,
                              y=rownames(reg)))+ 
  scale_fill_manual(breaks = r, # regulation information
                      values = col)+
  geom_bar(position="dodge", stat="identity")+
  labs(title = paste("regulation of pathways"), x = "mean expression based on genes on leading edge", y = "pathways")+
  theme(axis.text = element_text(size = 5))


 


grid.arrange(arrangeGrob(up.reg, down.reg), arrangeGrob(total_genes, s), ncol = 2)

up.reg
down.reg
total_genes
s
```

```{r reorder the df}
#creorder by mean expression of each pathway

reg2 = reg[(order(reg$mean)),]
reg2$order = c(1:dim(reg2)[1])
View(reg2)

#split into df with only up and only downregulated genes
reg2up = reg2[which(reg2$up_down== "up regulated"),]
reg2down = reg2[which(reg2$up_down== "down regulated"),]

for (i in 1:dim(reg2up)[1]){
  ifelse(reg2up$up[i] == 100.00,
         reg2up$regulation[i] <- "only upregulated",
         reg2up$regulation[i] <- "mostly upregulated")
}

for (i in 1:dim(reg2down)[1]){
  ifelse(reg2down$down[i] == 100.00,
         reg2down$regulation[i] <- "only downregulated",
         reg2down$regulation[i] <- "mostly downregulated")
}

reg2 = as.data.frame(rbind(reg2down, reg2up))

rm(reg2up, reg2down, i)
```


```{r dotplot and barplot}

r = c("mostly upregulated", "mostly downregulated","only upregulated", "only downregulated")# regulation info
col = c("orange","lightblue","violetred4",  "royalblue3")

dot = ggplot(reg2, aes(x = mean, y = order, size = number_of_genes, col = regulation))+
  geom_point(stat = "identity")+
  scale_color_manual(breaks = r,
                     values = col)+
  labs(title = paste("dotplot (mean)"), x = "mean expression rate (fold changes) of each pw", y = "pathways")+
  theme(axis.text = element_text(size = 7))+
  scale_y_discrete(limits = rownames(reg2))# to get the pws in the correct order somehow...

bar = ggplot(reg2, aes(fill= regulation, x = mean,
                              y=order))+ 
  scale_fill_manual(breaks = r, # regulation information
                      values = col)+
  geom_bar(position="dodge", stat="identity")+
  theme(axis.text = element_text(size =7))+
  labs(title = paste("barplot (mean)"), x = "mean expression rate (fold changes) of each pw", y = "pathways")+
  scale_y_discrete(limits = rownames(reg2))


grid.arrange(dot, bar, ncol = 2)

#same with medians:
reg3 = reg2[order(reg2$median),]
reg3$order = c(1:dim(reg3)[1])
View(reg3)


dot2 = ggplot(reg3, aes(x = median, y = order, size = number_of_genes, col = regulation))+
  geom_point(stat = "identity")+
  scale_color_manual(breaks = r,
                     values = col)+
  labs(title = paste("dotplot (median)"), x = "median expression rate (fold changes) of each pw", y = "pathways")+
  theme(axis.text = element_text(size = 7))+
  scale_y_discrete(limits = rownames(reg3))# to get the pws in the correct order somehow...

bar2 = ggplot(reg3, aes(fill= regulation, x = median,
                              y=order))+ 
  scale_fill_manual(breaks = r, # regulation information
                      values = col)+
  geom_bar(position="dodge", stat="identity")+
  theme(axis.text = element_text(size =7))+
  labs(title = paste("barplot (median)"), x = "median expression rate (fold changes) of each pw", y = "pathways")+
  scale_y_discrete(limits = rownames(reg3))


grid.arrange(dot2, bar2, ncol = 2)

grid.arrange(dot, dot2, ncol = 2)
grid.arrange(bar, bar2, ncol = 2)


```


```{r}
rm(dot2, bar2, reg3)
```

```{r boxplot with mean of pws}



gene_expr = c()
pathway = c()
n = c() #gonna be our vector for the gene names
for(i in 1 :length(genesets$genesets)){

x = i # choose pathway by position

pw = GSEA_p$pathway[x] 
pw

pw.genes = unlist(GSEA_p$leadingEdge[x], use.names = F)#genes in the pathway
genes = luad.info$name #all genes

positions = sort(match(pw.genes, genes))#compare to get positions
positions

selection = luad.info[pw.genes,] # select rows from data frame
selection$pathway = pw # make new column, called like the pw
gene_expr = append(gene_expr, selection$diff.mean)
pathway = append(pathway, selection$pathway)
#save the genenames into a new vector
n = append(n, rownames(selection))
}



boxplot_df = data.frame(genes = n,
                        gene_expr = gene_expr,
                        pw = pathway)

p <- ggplot(boxplot_df, aes(x=gene_expr, y=pathway))+
  geom_boxplot(fill = "lightskyblue", col="gray31",
               outlier.colour="red4", outlier.shape=20,
               outlier.size=2)+
  labs(title = paste("boxplot"), subtitle = "some genes are highlighted", x = "mean expression rates between tumor and normal tissue (fold changes) ", y = "pathways")+
  coord_flip()+ # flipping the plot
  theme(axis.text.x = element_text(size = 10, angle=90, hjust = 0.95, vjust = 0))+
  geom_vline(xintercept = 0, col = "red", lty = 1)


p
###now we want to label the outliers:

#1 get outliers from plot
outliers <- ggplot_build(p)[["data"]][[1]][["outliers"]]
#2 name the outlyers by pathway
names(outliers) <- levels(factor(boxplot_df$pw))
#3 convert to tidy data
tidy_out <- purrr::map_df(outliers, tibble::as_tibble, .id = "pw")
#4 look for our genes
g = boxplot_df$genes[match(tidy_out$value, boxplot_df$gene_expr)]
#5 rename tidyout df
tidy_out$gene_names = g
t2 = tidy_out
t3 = t2[match(unique(tidy_out$gene_names), t2$gene_names),]
t3 = t3[order(t3$value),]
dim(t3)
#lets pick the top 10 over-expressed and under-expresssed genes
t5 = rbind(head(t3,10), tail(t3,10))

p2 = p + geom_text(data = t5, aes(value, pw, label = gene_names), 
              hjust = -.3, size = 3, col = "red")+
  geom_point(data = t5, aes(value, pw ), col = "red")
p2

rm(gene_expr, pathway, p, t2,t3,t5,tidy_out, col, g, gene_expr, genes,i,n,positions,pw,pw.genes,r,x, outliers)
```
```{r select only most down and up regulated pws}
most_up_down = as.data.frame(rbind(head(reg2, 5), tail(reg2, 5)))
View(most_up_down)

pathways = rownames(most_up_down)
plots$pw.v.plots[pathways]

grid.arrange(grobs = plots$pw.v.plots[pathways])
```

