---
title: "focussed"
author: "Felipe Stünkel"
date: "30 5 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = F)
```

```{r load packages & data}
#install.packages("Seurat")

library(ggplot2)
library(scales)
library("gridExtra")
library(gtools)
library(parallel)
library(grid)
library(Seurat)
library(uwot)

LUAD_tumor_vs_norm_clean <- readRDS("./data/LUAD_tumor_vs_norm_clean.RDS")
luad.tumor = LUAD_tumor_vs_norm_clean[["luad.tumor.clean"]]
luad.normal = LUAD_tumor_vs_norm_clean[["luad.normal.clean"]]
luad.anno = LUAD_tumor_vs_norm_clean[["luad.anno"]]
```

```{r PCA with tumor genes}
pca = RunPCA(t(luad.tumor))
summary(pca)
dim(pca)
pc_tumor = as.data.frame(pca@cell.embeddings)

#check for genderspecific clustering in PC1 and PC 2
g.anno.gender = ggplot(pc_tumor, aes(PC_1, PC_2, colour = luad.anno$gender)) + 
  geom_point(size=4)
g.anno.gender

#check for race specific clustering
g.anno.race = ggplot(pc_tumor, aes(PC_1, PC_2, colour = luad.anno$race)) + 
  geom_point(size=2)
g.anno.race

#check for age specific clustering
g.anno.age = ggplot(pc_tumor, aes(PC_1, PC_2, colour = luad.anno$age_at_initial_pathologic_diagnosis)) + 
  geom_point(size=4)
g.anno.age

umap = as.data.frame(umap(pc_tumor))
class(umap)
#View(umap)

u.gender = ggplot(umap, aes(V1, V2, colour = luad.anno$gender)) + 
  geom_point(size=4)

grid.arrange(u.gender, g.anno.gender, nrow = 1)


#pca.var = pca$sdev^2
#pca.var.per = pca.var/sum(pca.var)*100
#barplot(pca.var.per, xlab = "PCs", ylab = "Percent variation")
#plot(pca$x[,1], pca$x[,2], pch = 20, size = .2)
```
```{r df with tumor and normal tissue}
tn = rbind(luad.normal, luad.tumor)

pca = RunPCA(t(tn))
summary(pca)
dim(pca)
pc_tn = as.data.frame(pca@cell.embeddings)
pc_tn

pc_tn_copy = select(pc_tn, PC_1, PC_2, PC_3, PC_4)

#add col with tissue type
tissue = c(1:(nrow(luad.normal)*2))
tissue[1:nrow(luad.normal)] = "normal"
tissue[(nrow(luad.normal)+1):(nrow(luad.normal)*2)] = "tumor"
pc_tn_copy$tissue = tissue

#add col with gender
gender = nrow(tissue)
gender[1:nrow(luad.normal)] = c(luad.anno$gender)
gender[(nrow(luad.normal)+1):(nrow(luad.normal)*2)] = c(luad.anno$gender)
pc_tn_copy$gender = gender

#add patients labeled with numbers
name = c(1:58, 1:58)
pc_tn_copy$names = name

g = ggplot(pc_tn_copy, aes(y = PC_1, PC_2, col = tissue, shape = gender))+
  labs(title = "PCA")+
  geom_point( size = 4)+
  geom_line(aes(group = name), col = "black", alpha = 0.2)
g
# we dont see a clustering in gender but we see that the normal tissue is clustered more narrowly than´the tumor tissue which can lead to believe that there could be subclasters

rm(tn, pca, pc_tn)
```


