---
title: "tumor_vs_normal_gsea"
author: "Chloé"
date: "31/05/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load all recquired packages & data}
#if you haven't yet installed fgsea package, run the following code

#if (!require("BiocManager", quietly = TRUE))
 #   install.packages("BiocManager")
#BiocManager::install("fgsea")

#to install cinaR, first run
#if (!require("BiocManager", quietly = TRUE))
    #install.packages("BiocManager")

#BiocManager::install("limma")
#if (!require("BiocManager", quietly = TRUE))
 #   install.packages("BiocManager")

#BiocManager::install("edgeR")

#install.packages("cinaR")

#to install enrichplot, first run
#if (!require("BiocManager", quietly = TRUE))
 #   install.packages("BiocManager")

#BiocManager::install("enrichplot")

#install.packages("tidyverse")

library(limma)
library(edgeR)
library(cinaR)
library(fgsea)
library(ggplot2)
library(biomaRt)
library(enrichplot)
library(tidyverse)
library(scales)
library("gridExtra")
library(gtools)
library(parallel)
library(grid)

LUAD_tumor_vs_norm_clean <- readRDS("./data/LUAD_tumor_vs_norm_clean.RDS")
luad.info = LUAD_tumor_vs_norm_clean[["infomatrix"]]


rm(LUAD_tumor_vs_norm_clean)
```

## create a sorted list of p-values

```{r ranked p-values}

#create a sorted list of p-values from wilcoxon test (see also: data cleanup)
sorted_p = sort(luad.info$p.wilc, decreasing = F)
head(sorted_p)

#finalise ranked p-values dataframe
ranked.pvalues = data.frame(p.wilc = sorted_p)
rownames(ranked.pvalues) = make.names(rownames(luad.info))
head(ranked.pvalues)

rm(sorted_p)
```

### Create a ranked list of log2 FC values

```{r}
#create a sorted list of log2 FC values from most upregulated to most downregulated (see also: data cleanup)
sorted_fc = sort(luad.info$diff.mean, decreasing = T)
head(sorted_fc)

ranked_fc = data.frame(diff.mean = sorted_fc)
rownames(ranked_fc) = make.names(rownames(luad.info))
head(ranked_fc)

rm(sorted_fc)
```

## run GSEA

#### GSEA mit p-Werten

```{r prepare and run GSEA}
#load genesets
metabolism_list_gs = readRDS("./data/metabolism_list_gs.RDS")
genesets <- readRDS("./data/hallmarks_genesets.rds")

genesets$genesets = append(genesets$genesets, metabolism_list_gs)

#stats argument (ranked p values) needs to be the right format
Names = rownames(ranked.pvalues)
Values = ranked.pvalues$p.wilc
names(Values) = Names

GSEA_p = fgsea(pathways = genesets$genesets, stats = Values, scoreType = "pos")

rm(Names, Values)

#View(GSEA)
```

Fehlermeldung beim obrigen Chunk: 70.51% der Liste sind ties

```{r Einschub: Überprüfung der Warnmeldung beim obrigen Chunk}
length(unique(ranked.pvalues$p.wilc)) #gibt die Anzahl der einzigartigen Werte in unserer Liste

#Berechnung des Anteils von einzigartigen p Values
length(unique(ranked.pvalues$p.wilc)) / length(ranked.pvalues$p.wilc) 
#18,65% der p values sind einzigartig

tail(sort(table(ranked.pvalues$p.wilc)),10) #gibt die 5 Werte die am meisten vorkommen und wie oft sie vorkommen
```

#### GSEA mit log2 FC

```{r}
# gleicher Code wir davor

Names_fc = rownames(ranked_fc)
Values_fc = ranked_fc$diff.mean
names(Values_fc) = Names_fc

GSEA_fc = fgsea(pathways = genesets$genesets, stats = Values, scoreType = "pos")

rm(Names_fc)
```

###volcano anfärben


```{r hoch expr gene ansehen}
LUAD_tumor_vs_norm_clean <- readRDS("./data/LUAD_tumor_vs_norm_clean.RDS")
luad.info = LUAD_tumor_vs_norm_clean[["infomatrix"]]
rm(LUAD_tumor_vs_norm_clean)


#naming the top over or under expressed genes
sp4 = ggplot(luad.info, aes(y = abs(spval), diff.mean, colour = expr, label = name))+
  geom_point(size = .5)+
  scale_color_manual(values=c("blue", "gray", "red"))+
  labs(title = "normal volcano plot", y = "fc", x = "pwilc")+
  geom_text(aes(label =
                  ifelse(abs(spval)>9 & abs(diff.mean)>5, as.character(name),""))
            )
sp4 # look at the highest fc genes

#x = grep("CA9", genesets$genesets) # example gene which is highly overexpressed
#names = names(genesets$genesets[x])
#names[1]
```


```{r pathways im volcano plot anfärben, saving all plots in a vector}

alpha = 0.05
alpha.corr = -log10(alpha/nrow(luad.info))


z = length(genesets$genesets)
pw.v.plots = list()
pw.sv.plots = list()
pw.grad.plots = list()
name = c()
regulation = data.frame(up = c(1:z),
                        down = c(1:z),
                        not_sign = c(1:z),
                        number_of_genes = c(1:z))


for(i in 1:z){
  # select genes from one pwathway
unique(GSEA_p$pathway) #all pathways
x = i # choose pathway by position

pw = GSEA_p$pathway[x] 
pw

pw.genes = unlist(GSEA_p$leadingEdge[x], use.names = F)#genes in the pathway
genes = luad.info$name #all genes

positions = sort(match(pw.genes, genes))#compare to get positions
positions

selection = luad.info[pw.genes,] # select rows from data frame
selection$pathway = pw # make new column, called like the pw

sel = luad.info$diff.mean[positions]#calculate mean expr of each pw
mean = mean(sel)  
median = median(sel)

col = c("slateblue4", "lightcoral", "slategray1", "gray84") # choosing the colours


#calculate % genes by up or down regulation
hits = paste(dim(selection)[1], "genes in", pw)
p.down = (length(which(selection$expr == "down"))/dim(selection)[1])*100
p.up = (length(which(selection$expr == "up"))/dim(selection)[1])*100

hits
percent.down = paste(round(p.down, digits = 2), "% down")
percent.up = paste(round(p.up, digits = 2), "% up")
rest = 100 - round(p.down, digits = 2) - round(p.up, digits = 2)
ns = paste(rest, "% not sign.")
vh = round(p.up/p.down, digits = 2)

#calculate for each pw the menan expression of the genes


#
##
####
##
#


###plots
#1 ) normaler v.plot
plot.v <- ggplot(luad.info, aes(y = abs(spval), diff.mean, colour = expr, label = name))+
  geom_point(size = .2)+
  labs(title = paste("volcano plot pw: ", pw), x = "fc", y = "pwilc")+
  scale_color_manual(name = "",
                     breaks = c(pw, "up", "down", "not sign."),
                     labels = c(hits, percent.up, percent.down, ns),
                     values = col )+ 
  geom_point(data = selection,
             aes(y = abs(spval), diff.mean, color = pathway), size = .7)
#2 ) singed volcano plot
plot.s = ggplot(luad.info, aes(y = spval, diff.mean, colour = expr))+
  geom_point(size = .5)+
  labs(title = paste("singed volcano plot pw: ", pw), x = "fc", y = "spval")+
  scale_color_manual(name = "",
                     breaks = c(pw, "up", "down", "not sign."),
                     labels = c(hits, percent.up, percent.down, ns),
                     values = col )+ 
  geom_point(data = selection,
             aes(y = spval, diff.mean, color = pathway), size = 1)
#3 ) gradient plot
plot.g = ggplot(luad.info, aes(spval, abs(diff.mean), colour = expr))+
  geom_point(size = .5)+
  labs(title = paste("gradient volcano plot pw: ", pw), x = "fc", y = "spval")+
  scale_color_manual(name = "",
                     breaks = c(pw, "up", "down", "not sign."),
                     labels = c(hits, percent.up, percent.down, ns),
                     values = col )+ 
  geom_point(data = selection,
             aes(spval, abs(diff.mean), color = pathway), size = 1)



###saving
pw.v.plots[[i]] <- plot.v #save the plot in the list element
pw.sv.plots[[i]] <- plot.s
pw.grad.plots[[i]] <- plot.g
message("plot saved")

regulation$up[i] = round(p.up, digits = 2)
regulation$down[i] = round(p.down, digits = 2)
regulation$not_sign[i] = rest
regulation$up_div_down[i] = vh
regulation$number_of_genes[i] = dim(selection)[1]
regulation$mean[i] = mean
regulation$median[i] = median

message("regulation filled")

name[i] <- paste(pw) #names for list elements
message("name saved")



}

#rename list elements
names(pw.v.plots) <- paste0(name, 1:length(pw.v.plots))
names(pw.sv.plots) <- paste0(name, 1:length(pw.sv.plots))
names(pw.grad.plots) <- paste0(name, 1:length(pw.grad.plots))

#new list object with all plots
plots = list(pw.v.plots = pw.v.plots, 
             pw.sv.plots = pw.sv.plots,
             pw.grad.plots = pw.grad.plots,
               description = list("1" = "vcolcano plots",
                                  "2" = "signed pvals volc plots",
                                  "3" = "gradient plots"),
             regulation = regulation)
rownames(plots$regulation) <- name


View(plots$regulation)



rm( z, x, pw, pw.genes,name, genes, positions, selection, col, i, hits, p.down, p.up, percent.up,percent.down, rest, ns, pw.v.plots, pw.sv.plots, pw.grad.plots, plot.v, plot.s, plot.g)
```

```{r print plots information in volcano plots etc}
#grid.arrange(grobs = (plots$pw.sv.plots[1:15]))
#grid.arrange(grobs = (plots$pw.v.plots[16:30]))
#grid.arrange(grobs = (plots$pw.grad.plots[31:46]))


reg = plots$regulation

up.reg = ggplot(reg, aes(fill=up, x=up, y=rownames(reg))) +
  geom_bar(position="dodge", stat="identity")+
  scale_fill_gradient(low = "thistle1", high = "violetred4")+
  labs(title = paste("comparison of up regulated genes"), x = "up.genes/genes.in.pw", y = "pathways")+
  scale_color_manual(name = "up")+
  xlim(0,60)+
  theme(axis.text = element_text(size = 5)) 

down.reg = ggplot(reg, aes(fill=down, x=down, y=rownames(reg))) + 
  geom_bar(position="dodge", stat="identity")+
  scale_fill_gradient(low = "lightblue", high = "purple4")+
  labs(title = paste("comparison of down regulated genes"), x = "down.genes/genes.in.pw", y = "pathways")+
  scale_color_manual(name = "down")+
  xlim(0,60)+
  theme(axis.text = element_text(size = 5))

total_genes = ggplot(reg, aes(fill= number_of_genes, x=number_of_genes,
                              y=rownames(reg))) + 
  geom_bar(position="dodge", stat="identity")+
  scale_fill_gradient(low = "lightblue", high = "slategray")+
  labs(title = paste("comparison in number of 'hits'"), x = "number of genes", y = "pathways")+
  scale_color_manual(name = "count")+
  theme(axis.text = element_text(size = 5))


#log10 tf
reg$singed_ratio = c(1:dim(reg)[1])
for(i in 1:dim(reg)[1]){
  ifelse(1 > reg$up_div_down[i] & reg$up_div_down[i] > 0,
         reg$singed_ratio[i] <- -(reg$up_div_down[i]^(-1)),
         reg$singed_ratio[i] <- reg$up_div_down[i]
         )
  }
reg$singed_ratio[which(reg$singed_ratio == 0)] <- -Inf

r = c("über.expr", "unter.expr","nur.über.expr", "nur.unter.expr","gleich")# regulation info
col = c("orange","lightblue","violetred4",  "royalblue3",  "green")

reg$regulation[which(reg$singed_ratio > 0)] <- r[1]
reg$regulation[which(reg$singed_ratio < 0)] <- r[2]
reg$regulation[which(reg$singed_ratio == Inf)] <- r[3]
reg$regulation[which(reg$singed_ratio == -Inf)] <- r[4]
reg$regulation[which(reg$singed_ratio == 1)] <- r[5]
View(reg)
s = ggplot(reg, aes(fill= regulation, x= singed_ratio,
                              y=rownames(reg)))+ 
  scale_fill_manual(breaks = r, # regulation information
                      values = col)+
  geom_bar(position="dodge", stat="identity")+
  labs(title = paste("more up or more down reg"), x = "regution level", y = "pathways")+
  theme(axis.text = element_text(size = 5))




grid.arrange(arrangeGrob(up.reg, down.reg), arrangeGrob(total_genes, s), ncol = 2)

up.reg
down.reg
total_genes
s
```

```{r dotplot and barplot}
#calculate the mean expression of each pathway

reg2 = reg[order(reg$mean),]
reg2$order = c(1:87)
View(reg2)


dot = ggplot(reg2, aes(x = mean, y = order, size = number_of_genes, col = regulation))+
  geom_point(stat = "identity")+
  scale_color_manual(breaks = r,
                     values = col)+
  labs(title = paste("dotplot (mean)"), x = "mean expression rate (fold changes) of each pw", y = "pathways")+
  theme(axis.text = element_text(size = 7))+
  scale_y_discrete(limits = rownames(reg2))# to get the pws in the correct order somehow...

bar = ggplot(reg2, aes(fill= regulation, x = mean,
                              y=order))+ 
  scale_fill_manual(breaks = r, # regulation information
                      values = col)+
  geom_bar(position="dodge", stat="identity")+
  theme(axis.text = element_text(size =7))+
  labs(title = paste("barplot (mean)"), x = "mean expression rate (fold changes) of each pw", y = "pathways")+
  scale_y_discrete(limits = rownames(reg2))


grid.arrange(dot, bar, ncol = 2)

#same with medians:
reg3 = reg[order(reg$median),]
reg3$order = c(1:87)
View(reg2)


dot2 = ggplot(reg3, aes(x = median, y = order, size = number_of_genes, col = regulation))+
  geom_point(stat = "identity")+
  scale_color_manual(breaks = r,
                     values = col)+
  labs(title = paste("dotplot (median)"), x = "median expression rate (fold changes) of each pw", y = "pathways")+
  theme(axis.text = element_text(size = 7))+
  scale_y_discrete(limits = rownames(reg3))# to get the pws in the correct order somehow...

bar2 = ggplot(reg3, aes(fill= regulation, x = median,
                              y=order))+ 
  scale_fill_manual(breaks = r, # regulation information
                      values = col)+
  geom_bar(position="dodge", stat="identity")+
  theme(axis.text = element_text(size =7))+
  labs(title = paste("barplot (median)"), x = "median expression rate (fold changes) of each pw", y = "pathways")+
  scale_y_discrete(limits = rownames(reg3))


grid.arrange(dot2, bar2, ncol = 2)

grid.arrange(dot, dot2, ncol = 2)
grid.arrange(bar, bar2, ncol = 2)

```

```{r boxplot with mean of pws}



gene_expr = c()
pathway = c()
n = c() #gonna be our vector for the gene names
for(i in 1 :length(genesets$genesets)){

x = i # choose pathway by position

pw = GSEA_p$pathway[x] 
pw

pw.genes = unlist(GSEA_p$leadingEdge[x], use.names = F)#genes in the pathway
genes = luad.info$name #all genes

positions = sort(match(pw.genes, genes))#compare to get positions
positions

selection = luad.info[pw.genes,] # select rows from data frame
selection$pathway = pw # make new column, called like the pw
gene_expr = append(gene_expr, selection$diff.mean)
pathway = append(pathway, selection$pathway)
#save the genenames into a new vector
n = append(n, rownames(selection))
}

boxplot_df = data.frame(genes = n,
                        gene_expr = gene_expr,
                        pw = pathway)

p <- ggplot(boxplot_df, aes(x=gene_expr, y=pathway))+
  geom_boxplot(fill = "lightskyblue", col="gray31",
               outlier.colour="red4", outlier.shape=20,
               outlier.size=2)+
  labs(title = paste("boxplot"), subtitle = "some genes are highlighted", x = "mean expression rates between tumor and normal tissue (fold changes) ", y = "pathways")+
  coord_flip()+ # flipping the plot
  theme(axis.text.x = element_text(size = 10, angle=90, hjust = 0.95, vjust = 0))+
  geom_vline(xintercept = 0, col = "red", lty = 1)


p
###now we want to label the outliers:

#1 get outliers from plot
outliers <- ggplot_build(p)[["data"]][[1]][["outliers"]]
#2 name the outlyers by pathway
names(outliers) <- levels(factor(boxplot_df$pw))
#3 convert to tidy data
tidy_out <- purrr::map_df(outliers, tibble::as_tibble, .id = "pw")
#4 look for our genes
g = boxplot_df$genes[match(tidy_out$value, boxplot_df$gene_expr)]
#5 rename tidyout df
tidy_out$gene_names = g
t2 = tidy_out
t3 = t2[match(unique(tidy_out$gene_names), t2$gene_names),]
t3 = t3[order(t3$value),]
dim(t3)
#lets pick the top 10 over-expressed and under-expresssed genes
t4 = rbind(t3[1:10,], t3[174:183,])


p2 = p + geom_text(data = t4, aes(value, pw, label = gene_names), 
              hjust = -.3, size = 3, col = "red")+
  geom_point(data = t4, aes(value, pw ), col = "red")
p2
```
```{r heatmap}
#were gonn plot a heatmap containing the expression rates for each gene in each pathway
library(pheatmap)

#our data:
head(boxplot_df)
length(unique(boxplot_df$genes))
```



```{r backup plots}

x = 1 # choose pathway by position

pw = GSEA_p$pathway[x] 
pw

pw.genes = unlist(GSEA_p$leadingEdge[x], use.names = F)#genes in the pathway
genes = luad.info$name #all genes

positions = sort(match(pw.genes, genes))#compare to get positions
positions

selection = luad.info[pw.genes,] # select rows from data frame
selection$pathway = pw # make new column, called like the pw

col = c("slateblue4", "lightcoral", "slategray1", "gray84") # choosing the colours

hits = paste(dim(selection)[1], "genes in", pw)
p.down = (length(which(selection$expr == "down"))/dim(selection)[1])*100
p.up = (length(which(selection$expr == "up"))/dim(selection)[1])*100

hits
precent.down = paste(round(p.down, digits = 2), "% down")
percent.up = paste(round(p.up, digits = 2), "% up")
rest = 100 - round(p.down, digits = 2) - round(p.up, digits = 2)
ns = paste(rest, "% not sign.")
#singed volcano plot
pw.volc2 = ggplot(luad.info, aes(y = spval, diff.mean, colour = expr))+
  geom_point(size = .5)+
  labs(title = paste("singed volcano plot pw: ", pw), x = "fc", y = "spval")+
  scale_color_manual(name = "title",
                     breaks = c(pw, "up", "down", "not sign."),
                     labels = c(hits, percent.up, precent.down, ns),
                     values = col )+ 
  geom_point(data = selection,
             aes(y = spval, diff.mean, color = pathway), size = 1)
pw.volc2




pw.volc3 = ggplot(luad.info, aes(spval, abs(diff.mean), colour = expr))+
  geom_point(size = .5)+
  labs(title = paste("gradient volcano plot pw: ", pw), x = "fc", y = "spval")+
  scale_color_manual(name = "title",
                     breaks = c(pw, "down", "not sign.", "up"),
                     labels = c(pw, "down", "not significant", "up"),
                     values = col )+ 
  geom_point(data = selection,
             aes(spval, abs(diff.mean), color = pathway), size = 1)


rm(x, pw, pw.genes, genes, positions, selection, col)


```

```{r saving plots on desktop!!}
### ACHTUNG!! for loop speichert plots! ###
####z = c(1:46)
####for(i in 1:length(z)){
    
  # select genes from one pwathway
unique(GSEA_p$pathway) #all pathways
x = i # choose pathway by position

pw = GSEA_p$pathway[x] 
pw

pw.genes = unlist(GSEA_p$leadingEdge[x], use.names = F)#genes in the pathway
genes = luad.info$name #all genes

positions = sort(match(pw.genes, genes))#compare to get positions
positions

selection = luad.info[pw.genes,] # select rows from data frame
selection$pathway = pw # make new column, called like the pw

col = c("slateblue4", "slategray1", "gray84", "lightcoral") # choosing the colours


#normaler v.plot
pw.volc = ggplot(luad.info, aes(y = abs(spval), diff.mean, colour = expr, label = name))+
  geom_point(size = .5)+
  labs(title = paste("volcano plot pw: ", pw), x = "fc", y = "pwilc")+
  scale_color_manual(name = "title",
                     breaks = c(pw, "down", "not sign.", "up"),
                     labels = c(pw, "down", "not significant", "up"),
                     values = col )+ 
  geom_point(data = selection,
             aes(y = abs(spval), diff.mean, color = pathway), size = 1)


####ggsave(path = "C:/Users/felip/Desktop/plots", filename = paste(pw, "_volcano.png"), plot = pw.volc)

####}

```


```{r informationen über die gene}
g = "EDN"
pos = grep(g,rownames(luad.info))
View(luad.info[pos,])


```

